### ISSUE TITLE
프로젝트 모든 VO 작성

### ISSUE THREAD

**Issue by rirasio** [rirasio/rocket#13]
모든 VO를 작성하겠습니다.

**Comment by rirasio** [comment]
과제학생(dohw)테이블 과제고유num 칼럼명(uphw_num) 확인해주세요. 
과제(hw)테이블 과제고유num 칼럼명(hw_num)과 같아야 하지 않을까요?
@k-fine @pdwon-seoul @qqruqq @Cciri

**Comment by pdwon-seoul** [comment]
> 과제학생(dohw)테이블 과제고유num 칼럼명(uphw_num) 확인해주세요.
> 과제(hw)테이블 과제고유num 칼럼명(hw_num)과 같아야 하지 않을까요?
> @k-fine @pdwon-seoul @qqruqq @Cciri

확인했습니다~ 수정할게요
