### ISSUE TITLE
우선 서버에서 페이지를 보이게 머스태치를 실험해보겠습니다

### ISSUE THREAD

**Issue by Cciri** [rirasio/rocket#15]
우선 서버에서 페이지를 보이게 머스태치를 실험해보겠습니다

**Comment by rirasio** [comment]
@Cciri 해결되었으니  이슈를 닫아도 좋을까요~?

**Comment by Cciri** [comment]
> @Cciri 해결되었으니 이슈를 닫아도 좋을까요~?

제가 하던 피처를 그냥 날리고 이슈만 닫아도 괜찮은거겠죠..?

**Comment by rirasio** [comment]
@Cciri 네~!
